# Generated by Django 3.2 on 2021-07-20 14:25

from django.db import migrations, models
import django.db.models.deletion
import taskmanager.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(default=taskmanager.models.genUrl, max_length=16)),
                ('color', models.CharField(default='#B5E61', max_length=7)),
                ('borderColor', models.CharField(max_length=7)),
                ('password', models.CharField(default='', max_length=200)),
                ('passwordNeeded', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('singupDate', models.DateTimeField(auto_now_add=True)),
                ('profImg', models.CharField(default='/img/profile.png', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TaskColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(default='', max_length=7)),
                ('tableId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskmanager.tables')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskmanager.user')),
            ],
        ),
        migrations.CreateModel(
            name='Particip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joinedDate', models.DateTimeField(auto_now_add=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskmanager.taskcolor')),
                ('tableId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskmanager.tables')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskmanager.user')),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tableNote', models.CharField(default='', max_length=500)),
                ('addedDate', models.DateTimeField(auto_now_add=True)),
                ('todoDate_start', models.DateTimeField(blank=True)),
                ('tableId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskmanager.tables')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskmanager.user')),
            ],
        ),
    ]
