# Generated by Django 3.2 on 2021-07-13 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0003_auto_20210713_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='singupDate',
            field=models.DateTimeField(),
        ),
    ]
