# Generated by Django 3.2 on 2021-07-13 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0004_alter_user_singupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='singupDate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
