# Generated by Django 3.2 on 2021-07-14 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0007_alter_user_singupdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Particip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tableId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskmanager.tables')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskmanager.user')),
            ],
        ),
    ]
