# Generated by Django 3.2 on 2021-07-14 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0008_particip_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='tables',
            name='url',
            field=models.CharField(default='hex(randomblob(16))', max_length=16),
        ),
    ]
