# Generated by Django 3.2 on 2021-07-14 23:57

from django.db import migrations, models
import taskmanager.db.Db


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0009_tables_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tables',
            name='url',
            field=models.CharField(default=taskmanager.db.Db.genUrl, max_length=16),
        ),
    ]
