# Generated by Django 3.2 on 2021-07-15 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0010_alter_tables_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='tables',
            name='color',
            field=models.CharField(default='#ECE36C', max_length=16),
        ),
    ]
