# Generated by Django 3.2 on 2021-07-15 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0011_tables_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tables',
            name='color',
            field=models.CharField(default='#B5E61', max_length=16),
        ),
    ]
