# Generated by Django 3.2 on 2021-07-15 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0013_tables_bordercolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profImg',
            field=models.CharField(default='/static/img/profile.png', max_length=100),
        ),
        migrations.AlterField(
            model_name='tables',
            name='borderColor',
            field=models.CharField(default='#8CAE22', max_length=7),
        ),
        migrations.AlterField(
            model_name='tables',
            name='color',
            field=models.CharField(default='#B5E61', max_length=7),
        ),
    ]
