# Generated by Django 3.2 on 2021-07-15 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0014_auto_20210715_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='singupDate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
