# Generated by Django 3.2 on 2021-07-15 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0015_alter_user_singupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='singupDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
