# Generated by Django 3.2 on 2021-07-16 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0016_alter_user_singupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tables',
            name='borderColor',
            field=models.CharField(max_length=7),
        ),
    ]
