# Generated by Django 3.2 on 2021-07-16 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0017_alter_tables_bordercolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='tables',
            name='password',
            field=models.CharField(default='', max_length=200),
        ),
    ]
