# Generated by Django 3.2 on 2021-07-20 12:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0018_tables_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='particip',
            name='joinedDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tables',
            name='passwordNeeded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='profImg',
            field=models.CharField(default='/img/profile.png', max_length=100),
        ),
        migrations.CreateModel(
            name='TaskColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(default='', max_length=7)),
                ('tableId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskmanager.tables')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskmanager.user')),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tableNote', models.CharField(default='', max_length=500)),
                ('addedDate', models.DateTimeField(auto_now_add=True)),
                ('todoDate', models.DateTimeField(blank=True)),
                ('tableId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskmanager.tables')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskmanager.user')),
            ],
        ),
        migrations.AddField(
            model_name='particip',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskmanager.taskcolor'),
            preserve_default=False,
        ),
    ]
